# Generated by Django 3.2.9 on 2021-11-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211112_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='leilao_finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lote',
            name='autor',
            field=models.CharField(default='Autor', max_length=200),
        ),
        migrations.AlterField(
            model_name='lote',
            name='editora',
            field=models.CharField(default='Editora', max_length=200),
        ),
    ]
