# Generated by Django 3.2.9 on 2021-11-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_pagamento_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='lote_foi_vendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lote',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
