# Generated by Django 3.2.8 on 2021-10-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leiloeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.DecimalField(decimal_places=0, max_digits=11)),
                ('bio', models.TextField()),
            ],
        ),
    ]
