# Generated by Django 3.2.8 on 2021-10-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='estadoConservacao',
            new_name='estado_conservacao',
        ),
        migrations.RenameField(
            model_name='lote',
            old_name='valorReserva',
            new_name='valor_reserva',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='leiloeiro',
            name='senha',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sobrenome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='username',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='leiloeiro',
            name='nome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='leiloeiro',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='leiloeiro',
            name='sobrenome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='leiloeiro',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
