# Generated by Django 3.2.8 on 2021-10-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_catalogo_destinatario_geracaoderelatorio_lance_leilao_listado_lote_notificacao_ofertado_ofertalotesd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
