# Generated by Django 3.2.9 on 2021-11-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211102_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='liberado_para_lances',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lote',
            name='numero_de_lances',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=11),
        ),
    ]
