# Generated by Django 3.2.9 on 2021-11-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211111_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='tipo_de_pagamento',
            field=models.TextField(choices=[('COMISSÃO NOVO LOTE', 'COMISSÃO NOVO LOTE'), ('COMISSÃO LANCE', 'COMISSÃO LANCE')], default='COMISSÃO NOVO LOTE'),
        ),
    ]
