# Generated by Django 3.2.9 on 2021-11-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211119_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='data_final',
            field=models.DateTimeField(null=True),
        ),
    ]
